### ISSUE TITLE
Additional creatures 

### ISSUE THREAD

**Issue by tharric** [kufii/Druidshape-5e#15]
Any plans on adding additional creatures from other source books?

**Comment by kufii** [comment]
Legally, I actually can't put them in the app. I can only add content that's in the [Systems Reference Document](https://dnd.wizards.com/articles/features/systems-reference-document-srd)

I did create a document containing some extra beasts that you can manually import:

https://github.com/kufii/Druidshape-5e/blob/master/src/data/volos.json
